### PR TITLE
Ticket 5266: Reconnect daqmx on error

### PR DESCRIPTION
**Pull request by DominicOram**
See https://github.com/ISISComputingGroup/IBEX/issues/5266. Added some VIs for starting and stopping a simulated NI MAX

To test:
* Open NI MAX
* Run `start_sim.bat`
* Confirm a new device and associated task appear as per http://www.ni.com/tutorial/3698/en/
* Run `stop_sim.bat` and confirm it disappears
* Open `DAQmx Simulator.lvproj` and confirm you can rebuild the exe

### CODE REVIEW

**Comment by Tom-Willemsen** [comment]
I am getting a nasty-looking crash from `start_sim.exe` both when running via the IOCTestFramework and running manually.

image

Logs at `shares\ISIS_Experiment_Controls\data for tickets\Ticket5266_daqmx`

I rebuilt locally in case it was just linking against a different version of labview/daqmx but got the same crash. I do have NI-MAX installed and open.

**Comment by DominicOram** [comment]
If you start the VI on its own does it run?

**Comment by Tom-Willemsen** [comment]
Yes, the standalone VI does seem to run and then stop as expected without crashing in that way.

To be clear, despite the crash the `exe` does still manage to create the simulated DAQ and the tests do pass... but I would be worried about leaving lots of broken processes on a build server.

**Comment by Tom-Willemsen** [comment]
With help from @KathrynBaker we found that we needed to add a ~15s sleep in between the simulated device being started and the VI exiting - this avoids the crash.

**Review by Tom-Willemsen — APPROVED** [review]

**Pull request merged**
